### ISSUE TITLE
游戏界面错误

### ISSUE THREAD

**Issue by wangjie11** [m-Ryan/egret-game#1]
修改maxRow和maxColumn后元素位置产生重叠

**Comment by m-Ryan** [comment]
> 修改maxRow和maxColumn后元素位置产生重叠
不好意思，没留意到有issue。
你好，我看了一下元素位置产生重叠的现象，大概是因为maxRow大于maxColumn，由于设计的时候为了方便计算，默认了maxRow 和 maxColumn 是相等。如果同时改变maxRow 和 maxColumn 是没有这个问题的。 如果你想设置 长宽不等， 可以在  resource/chapterMap.json  设置 关卡的地图元素

**Comment by m-Ryan** [comment]
> 修改maxRow和maxColumn后元素位置产生重叠

修改maxRow和maxColumn后元素位置产生重叠
不好意思，没留意到有issue。
你好，我看了一下元素位置产生重叠的现象，大概是因为maxRow大于maxColumn，由于设计的时候为了方便计算，默认了maxRow 和 maxColumn 是相等。如果同时改变maxRow 和 maxColumn 是没有这个问题的。 如果你想设置 长宽不等， 可以在 resource/chapterMap.json 设置 关卡的地图元素

**Comment by m-Ryan** [comment]
> 修改maxRow和maxColumn后元素位置产生重叠
@wangjie11 
不好意思，没留意到有issue。
你好，我看了一下元素位置产生重叠的现象，大概是因为maxRow大于maxColumn，由于设计的时候为了方便计算，默认了maxRow 和 maxColumn 是相等。如果同时改变maxRow 和 maxColumn 是没有这个问题的。 如果你想设置 长宽不等， 可以在 resource/chapterMap.json 设置 关卡的地图元素

**Comment by m-Ryan** [comment]
> 修改maxRow和maxColumn后元素位置产生重叠
@wangjie11 
不好意思，没留意到有issue。
你好，我看了一下元素位置产生重叠的现象，大概是因为maxRow大于maxColumn，由于设计的时候为了方便计算，默认了maxRow 和 maxColumn 是相等。如果同时改变maxRow 和 maxColumn 是没有这个问题的。 如果你想设置 长宽不等， 可以在 resource/chapterMap.json 设置 关卡的地图元素
